name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.1
        with:
         fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2.0.1
        with:
          firstParent: true
          failOnWarnings: true 

